import HanziWriter from "hanzi-writer";
import { wordsData } from "../data/words";
import type { Word } from "../types";

const HANZI = /[\u3400-\u9fff]/;
const words = wordsData as Word[];

type Point = [number, number];
type Candidate = { character: string; strokes: Point[][] };

declare global { interface Window { __hanziFeaturesInstalled?: boolean } }

const css = `
.clickable-hanzi{appearance:none;border:0;border-bottom:1px dotted currentColor;background:transparent;color:inherit;font:inherit;padding:0 .02em;cursor:pointer}
.hanzi-overlay{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;padding:18px;background:#1f1d1b8c;backdrop-filter:blur(5px)}
.hanzi-panel{width:min(100%,420px);max-height:92vh;overflow:auto;background:#fffdfa;border-radius:22px;padding:18px;box-shadow:0 24px 70px #0004;color:#373534}
.hanzi-panel-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.hanzi-panel-head button{width:38px;height:38px;border:0;border-radius:50%;font-size:1.35rem}
.hanzi-writer-target{width:280px;height:280px;max-width:100%;margin:auto;border:1px solid #ddd8d2;border-radius:16px;overflow:hidden;background:white}
.hanzi-actions{display:flex;gap:10px;margin-top:12px}.hanzi-actions button,.draw-search-open{border:0;border-radius:14px;padding:12px 14px;font-weight:700}.hanzi-actions button{flex:1;background:#373534;color:white}
.blank-practice{margin:18px 0 6px}.blank-practice>p{text-align:center;color:#6d6863}.blank-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(116px,1fr));gap:10px}.blank-box{display:grid;gap:6px}.blank-box canvas,.draw-search-canvas{width:100%;aspect-ratio:1;border:1.5px solid #cfc8c0;border-radius:15px;background:#fff;touch-action:none;user-select:none;-webkit-user-select:none}.blank-box small{text-align:center;color:#77716b}.blank-clear{display:block;margin:10px auto 0;border:0;background:transparent;text-decoration:underline}
.draw-search-open{margin-left:8px;background:#eee8e1;color:#373534}.draw-results{display:grid;grid-template-columns:repeat(8,1fr);gap:7px;margin-top:12px}.draw-results button{aspect-ratio:1;border:1px solid #ddd8d2;border-radius:10px;background:white;font-size:1.35rem}.draw-help{font-size:.9rem;color:#6d6863}
`;

function addStyles(){if(document.getElementById("hanzi-feature-css"))return;const s=document.createElement("style");s.id="hanzi-feature-css";s.textContent=css;document.head.append(s)}
function chars(value:string){return [...value].filter(c=>HANZI.test(c))}
function overlay(title:string){const bg=document.createElement("div");bg.className="hanzi-overlay";const panel=document.createElement("div");panel.className="hanzi-panel";const head=document.createElement("div");head.className="hanzi-panel-head";const strong=document.createElement("strong");strong.textContent=title;const close=document.createElement("button");close.textContent="×";close.onclick=()=>bg.remove();head.append(strong,close);panel.append(head);bg.append(panel);bg.onclick=e=>{if(e.target===bg)bg.remove()};document.body.append(bg);return panel}

function showStroke(character:string){const panel=overlay(`Schrijfwijze van ${character}`);const target=document.createElement("div");target.className="hanzi-writer-target";const actions=document.createElement("div");actions.className="hanzi-actions";const replay=document.createElement("button");replay.textContent="↻ Opnieuw";actions.append(replay);panel.append(target,actions);const writer=HanziWriter.create(target,character,{width:280,height:280,padding:18,showCharacter:false,showOutline:true,strokeColor:"#373534",outlineColor:"#ddd8d2",radicalColor:"#a66a57",strokeAnimationSpeed:1,delayBetweenStrokes:220,charDataLoader:async char=>{const r=await fetch(`/hanzi-data/${encodeURIComponent(char)}.json`);if(!r.ok)throw new Error();return r.json()}});const play=()=>{writer.hideCharacter();writer.animateCharacter()};replay.onclick=play;requestAnimationFrame(play)}

function wireCanvas(canvas:HTMLCanvasElement,onChange?:(strokes:Point[][])=>void){const ctx=canvas.getContext("2d")!;let active:Point[]|null=null;const strokes:Point[][]=[];const resize=()=>{const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);ctx.lineWidth=5;ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="#373534";redraw()};const redraw=()=>{ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);ctx.beginPath();for(const stroke of strokes){stroke.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p))}ctx.stroke()};const point=(e:PointerEvent):Point=>{const r=canvas.getBoundingClientRect();return[e.clientX-r.left,e.clientY-r.top]};canvas.onpointerdown=e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);active=[point(e)];strokes.push(active);redraw()};canvas.onpointermove=e=>{if(!active)return;e.preventDefault();active.push(point(e));redraw()};const finish=()=>{if(!active)return;active=null;onChange?.(strokes)};canvas.onpointerup=finish;canvas.onpointercancel=finish;canvas.onlostpointercapture=finish;resize();return{clear(){strokes.splice(0);redraw();onChange?.(strokes)}}}

function normalize(strokes:Point[][]){const all=strokes.flat();if(!all.length)return[];const xs=all.map(p=>p[0]),ys=all.map(p=>p[1]);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),scale=Math.max(maxX-minX,maxY-minY)||1;const resample=(pts:Point[],n=8)=>{if(pts.length===1)return Array.from({length:n},()=>pts[0]);const lens=[0];for(let i=1;i<pts.length;i++)lens.push(lens[i-1]+Math.hypot(pts[i][0]-pts[i-1][0],pts[i][1]-pts[i-1][1]));const total=lens.at(-1)||1;return Array.from({length:n},(_,k)=>{const t=total*k/(n-1);let j=1;while(j<lens.length&&lens[j]<t)j++;const a=Math.max(0,j-1),span=(lens[j]??total)-lens[a]||1,q=(t-lens[a])/span,p1=pts[a],p2=pts[Math.min(j,pts.length-1)];return[p1[0]+(p2[0]-p1[0])*q,p1[1]+(p2[1]-p1[1])*q] as Point})};return strokes.filter(s=>s.length).map(s=>resample(s).map(([x,y])=>[(x-minX)/scale,(y-minY)/scale] as Point))}
function distance(a:Point[][],b:Point[][]){if(a.length!==b.length)return 999;let total=0;for(let i=0;i<a.length;i++){for(let j=0;j<a[i].length;j++)total+=Math.hypot(a[i][j][0]-b[i][j][0],a[i][j][1]-b[i][j][1])}return total}

async function openDrawingSearch(input:HTMLInputElement){const panel=overlay("Zoek door een karakter te tekenen");const help=document.createElement("p");help.className="draw-help";help.textContent="Teken één Chinees karakter. Kies daarna de beste herkenning.";const canvas=document.createElement("canvas");canvas.className="draw-search-canvas";const results=document.createElement("div");results.className="draw-results";const actions=document.createElement("div");actions.className="hanzi-actions";const clear=document.createElement("button");clear.textContent="Wissen";actions.append(clear);panel.append(help,canvas,results,actions);const index=await fetch("/hanzi-data/recognition-index.json").then(r=>r.json()) as Candidate[];const draw=wireCanvas(canvas,strokes=>{const sample=normalize(strokes);const best=index.filter(c=>Math.abs(c.strokes.length-sample.length)<=1).map(c=>({c,d:distance(sample,c.strokes)})).sort((x,y)=>x.d-y.d).slice(0,24);results.replaceChildren(...best.map(({c})=>{const b=document.createElement("button");b.textContent=c.character;b.onclick=()=>{input.value+=c.character;input.dispatchEvent(new Event("input",{bubbles:true}));input.focus();document.querySelector(".hanzi-overlay")?.remove()};return b}))});clear.onclick=()=>draw.clear()}

function enhanceTheory(){const root=document.querySelector(".article-reader");if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>{const p=n.parentElement,t=n.textContent||"";return p&&HANZI.test(t)&&!p.closest("button,.clickable-hanzi,script,style,input,textarea")?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});const nodes:Text[]=[];while(walker.nextNode())nodes.push(walker.currentNode as Text);for(const node of nodes){const f=document.createDocumentFragment();for(const c of [...(node.textContent||"")]){if(!HANZI.test(c)){f.append(c);continue}const b=document.createElement("button");b.className="clickable-hanzi";b.textContent=c;b.ariaLabel=`Bekijk schrijfwijze van ${c}`;b.onclick=()=>showStroke(c);f.append(b)}node.replaceWith(f)}}

function sessionWord(){try{const s=JSON.parse(localStorage.getItem("chinees.learning-session.v1")||"null");const ex=s?.queue?.[s.index];if(s?.direction!=="nl-zh"||s?.revealed||!ex)return null;return words.find(w=>w.id===ex.wordId)||null}catch{return null}}
function enhancePractice(){const card=document.querySelector(".flashcard");if(!card)return;const word=sessionWord();const existing=document.querySelector(".blank-practice") as HTMLElement|null;if(!word){existing?.remove();return}const wordKey=String(word.id);if(existing?.dataset.wordId===wordKey)return;existing?.remove();const reveal=card.querySelector(".reveal-button");if(!reveal)return;const wrap=document.createElement("div");wrap.className="blank-practice";wrap.dataset.wordId=wordKey;const p=document.createElement("p");p.textContent="Teken elk benodigd karakter uit het hoofd.";const row=document.createElement("div");row.className="blank-row";const controls:{clear:()=>void}[]=[];chars(word.hanzi).forEach((_,i)=>{const box=document.createElement("div");box.className="blank-box";const canvas=document.createElement("canvas");const label=document.createElement("small");label.textContent=`Karakter ${i+1}`;box.append(canvas,label);row.append(box);controls.push(wireCanvas(canvas))});const clear=document.createElement("button");clear.className="blank-clear";clear.textContent="Wis alle tekenvlakken";clear.onclick=()=>controls.forEach(c=>c.clear());wrap.append(p,row,clear);reveal.before(wrap);document.querySelectorAll(".answer-block .audio-button").forEach(e=>(e as HTMLElement).style.display="none")}

function enhanceWordSearch(){const input=document.querySelector('.words-page .search-box input') as HTMLInputElement|null;if(!input||document.querySelector(".draw-search-open"))return;const b=document.createElement("button");b.type="button";b.className="draw-search-open";b.textContent="✎ Teken karakter";b.onclick=()=>openDrawingSearch(input);input.closest(".search-box")?.insertAdjacentElement("afterend",b)}

function enhance(){enhanceTheory();enhancePractice();enhanceWordSearch()}
export function installHanziFeatures(){if(window.__hanziFeaturesInstalled)return;window.__hanziFeaturesInstalled=true;addStyles();let scheduled=false;const scheduleEnhance=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;enhance()})};new MutationObserver(scheduleEnhance).observe(document.body,{childList:true,subtree:true});enhance()}
